//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventura.HR.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonUser : User
    {
        public short Age { get; set; }
        public string CPF { get; set; }
    }
}
