//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventura.RH.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criteria
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short PWD { get; set; }
        public short Weight { get; set; }
        public int OpportunityId { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
    }
}
